### ISSUE TITLE
Request: please may we have a 3.7.0 release to include the Qt6 fixes?

### ISSUE THREAD

**Issue by SlySven** [communi/libcommuni#109]
I am looking to prepare our **[Mudlet](https://github.com/Mudlet/Mudlet.git)** project for Qt6 and we are currently using the **libcommuni v3.6.0** tagged version. As such there are some things that don't compile in Qt6 in that version that I can see you believe you have fixed in later commits - and I would like to pull those in and it would be cleaner if I could point our project to an identifiable version.

Thanks again for making this library available.

**Comment by jpnurmi** [comment]
Will do later

**Comment by jpnurmi** [comment]
https://github.com/communi/libcommuni/releases/tag/v3.7.0
