### ISSUE TITLE
Ability to suppress any event in rooms.

### ISSUE THREAD

**Issue by mschaaf** [communi/libcommuni#41]
I always see events like "a joins #b" or "c sets mode +v b". I tried the following: I disabled show events in the settings and I enabled them and played with the user amount but no combination let me suppress the events.

Is it possible to suppress all events and if yes how is it possible?

**Comment by jpnurmi** [comment]
Sorry, [communi-sailfish](https://github.com/communi/communi-sailfish) is no longer maintained. Should anyone take over the maintenance in the future, this bug should be transferred to the correct project.
