### ISSUE TITLE
Automatically login to previously joined channels

### ISSUE THREAD

**Issue by mschaaf** [communi/libcommuni#42]
I use the gitter IRC server and it seems not to remember my joined channels. An option to mark some channels to automatically join on start up would be nice. Thanks for the great tool.

**Comment by jpnurmi** [comment]
Sorry, [communi-sailfish](https://github.com/communi/communi-sailfish) is no longer maintained. Should anyone take over the maintenance in the future, this bug should be transferred to the correct project.
