### ISSUE TITLE
Communi library is not found after installation

### ISSUE THREAD

**Issue by genesis231** [communi/libcommuni#47]
After building and installing Communi using:-
$ qmake
$ make
$ sudo make install

It's not detecting, while compiling spectrum2. Although it has been compiled already.

**Comment by jpnurmi** [comment]
Hi, is spectrum2 still based on the libcommuni 2.x branch? Try ```git checkout 2.2``` and repeat the steps.

**Comment by jpnurmi** [comment]
No further comments, so I'll assume the issue got resolved.
