### ISSUE TITLE
Somewhat ambigous qmake project names

### ISSUE THREAD

**Issue by SlySven** [communi/libcommuni#55]
Thank you for making this project available!  We are using it in our MUD client [Mudlet](https://github.com/Mudlet/Mudlet) but we are encountering a little bit of confusion in the Qt IDE where it uses the name of the qmake `.pro`/`.pri` project files as the actual name of the project/sub-project.

Currently our main project file as well as a couple of sub-projects are all being displayed as "__src__" - whilst we are only using the core of your work so we also have "__core__" as a sub-project in ours - would you consider renaming that to perhaps be "communi-core" - I realise that the parent/master/main project file for libcommuni is called `libcommuni.pro` and beneath that you have `src.pro`/`src.pri` and then beneath that `core.pri`/`core.pro` but I note you previously called the middle level ones `communi` not `src` and I was hoping that you might consider some renames so that all the qmake project files contain a "communi" substring and so any one using your project as part of theirs can be clear in Qt Creator which bits are from Communi and which are from something else. 😄

**Comment by jpnurmi** [comment]
This is pretty standard naming convention in the Qt world. :) You could create a file called `communi.pri` and put `include(path/to/libcommuni/src/core/core.pri)` there, and then Qt Creator will organize the respective files under a "communi" node.

**Comment by jpnurmi** [comment]
Looks like the workaround proposal was accepted. :)
