### ISSUE TITLE
Warnings 'overriding commands for target' when building on macOS

### ISSUE THREAD

**Issue by Timac** [communi/libcommuni#58]
Steps to reproduce:

1. Download the attached libcommuniTest project
2. Unzip it and open libcommuniTest/libcommuniTest/libcommuniTest.pro.
3. Compile it on macOS 10.12 or later using Qt Creator 4.4.0

Result: You will see 10 warnings like
 
```
libcommuniTest/build-libcommuniTest-Desktop_Qt_5_9_1_clang_64bit-Debug/Makefile:916: warning: overriding commands for target `moc_ircbuffer.cpp'
libcommuniTest/build-libcommuniTest-Desktop_Qt_5_9_1_clang_64bit-Debug/Makefile:858: warning: ignoring old commands for target `moc_ircbuffer.cpp'
```

[libcommuniTest.zip](https://github.com/communi/libcommuni/files/1404345/libcommuniTest.zip)

**Comment by jpnurmi** [comment]
Thanks! Fixed by https://github.com/jpnurmi/libcommuni/commit/5dac4e0a5f37a45accd6df4f0507e3f9caf42440.

**Comment by jpnurmi** [comment]
I just found out that this fix had never actually made it from my personal fork to the official repo. Sorry :)
