### ISSUE TITLE
Headless installation?

### ISSUE THREAD

**Issue by sdfg2** [communi/libcommuni#62]
I need libcommuni for spectrum2 on a headless server.  Is there anyway to not drag in every dependency up to and including mesa and wayland?

**Comment by jpnurmi** [comment]
We have no control over how Linux distributions organize their packages and dependencies, but if you are building libcommuni yourself, you may choose to build the parts you need. The core communi libraries depend on QtCore and QtNetwork only - not on Mesa, Wayland, or anything else GUI. However, in addition to the core libraries, the project includes an optional QML module that will be only built if the Qt installation has QtQml available. Furthermore, there's a QtQuick based UI example, that can be easily left out by passing `-nomake examples` to configure.

**Comment by jpnurmi** [comment]
I have added `-nomake qml` to make it straight-forward to exclude the QML plugin. Any ready-made distribution packages should be split so that backend libs and UI examples are provided separately.
