### ISSUE TITLE
Translation / internationalisation / localisation

### ISSUE THREAD

**Issue by Kebap** [communi/libcommuni#65]
So we are using libcommuni as part of the [Mudlet](https://github.com/Mudlet/Mudlet) game client.

As we are localizing Mudlet, we are also looking at your strings, and find some hard to grasp.

Examples:
1. `! %2 invited to %3`
2. `! %1 sets mode %2 %3 %4`
3. `* %1 %2`

Have you maybe already come up with a set of translations?

Indeed for many of these strings it would probably have been better to have used a `QStringLiteral` instead of `tr` as they are assembling a sentence in chunks and that usually does not fly well with i18n. Without further knowledge of what each replacement value is, it is not clear that translation is going to work here. 

What work has been done to internationalise the libcommuni project...? How should we report our (tries at) translations back upstream to you?

**Comment by jpnurmi** [comment]
Hi, are you referring to the code in libcommuni examples? It was meant to be used as a rough starting point for products that may want to use i18n.

**Comment by Kebap** [comment]
Thanks jpnurmi, this has clarified the issue a bit. I will look into it more and see how to fix the matter then.
