### ISSUE TITLE
'Multiplication result converted to larger type' warning

### ISSUE THREAD

**Issue by vadi2** [communi/libcommuni#91]
We run CodeQL on our Mudlet repository, and we make use of this excellent library as well. CodeQL brings up a warning for https://github.com/Mudlet/Mudlet/blob/0aa3f1b568084bf0d451920686cfad09700281e1/3rdparty/communi/src/util/irclagtimer.cpp#L104-L104:

>  Multiplication result may overflow 'int' before it is converted to 'qint64'. 

Rule explanation:

![image](https://user-images.githubusercontent.com/110988/99376582-68fcd300-28c5-11eb-920b-76eadda494f3.png)

**Comment by jpnurmi** [comment]
Thanks! Feel free to push a quick fix as proposed by CodeQL, and we'll get it approved and merged right away. :)

**Comment by jpnurmi** [comment]
Fixed by #95
